@echo off
REM ============================================================================
REM  bfx-ingest.bat - turn a folder into one AI-ready context file.
REM
REM  HOW TO USE (no install, nothing to set up):
REM    * Double-click this file and pick a folder, OR
REM    * Drag a folder ONTO this file.
REM  It writes <foldername>-context.md next to that folder and opens it.
REM
REM  This is a batch + PowerShell file in one. The batch part below just hands
REM  the PowerShell part (everything after the marker line below) to PowerShell,
REM  which every Windows machine already has. Your files never leave your PC.
REM ============================================================================
setlocal
set "BFX_DROP=%~1"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$t=[IO.File]::ReadAllText('%~f0'); $m=[char]35+'PSSTART'+[char]35; iex $t.Substring($t.IndexOf($m)+$m.Length)"
echo.
pause
exit /b
#PSSTART#
# ===== bfx-ingest (PowerShell): folder -> one Markdown context file ==========
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms | Out-Null

# 1) Decide which folder: the one dropped on the .bat, else ask with a dialog.
$root = $env:BFX_DROP
if (-not $root -or -not (Test-Path -LiteralPath $root -PathType Container)) {
  $dlg = New-Object System.Windows.Forms.FolderBrowserDialog
  $dlg.Description = 'Pick a folder to turn into AI context'
  $dlg.ShowNewFolderButton = $false
  if ($dlg.ShowDialog() -ne [System.Windows.Forms.DialogResult]::OK) { Write-Host 'Cancelled - no folder chosen.'; return }
  $root = $dlg.SelectedPath
}
$root = (Resolve-Path -LiteralPath $root).Path
$srcName = Split-Path -Leaf $root
Write-Host ("Reading {0} ..." -f $root)

# 2) What to skip (mirrors the bfx-ingest CLI/web versions).
$skipDirs = @('.git','node_modules','dist','build','.next','.cache','coverage','vendor','bfx-out','.venv','__pycache__')
$skipExt  = '\.(png|jpe?g|gif|webp|ico|svg|pdf|zip|gz|tar|rar|7z|mp4|mov|webm|mp3|wav|ogg|woff2?|ttf|eot|otf|exe|dll|so|dylib|bin|wasm|class|o|a|lib|map)$'
$maxBytes = 256 * 1024
$FENCE = @{ js='javascript'; ts='typescript'; jsx='jsx'; tsx='tsx'; py='python'; rb='ruby'; go='go'; rs='rust'; java='java'; c='c'; h='c'; cpp='cpp'; cs='csharp'; php='php'; sh='bash'; json='json'; yml='yaml'; yaml='yaml'; md='markdown'; html='html'; css='css'; sql='sql' }

# FNV-1a (32-bit): same hash the other bfx-ingest versions use, so identical
# files collapse to one body (the token savings).
function Get-Fnv([string]$s) {
  # NOTE: 0xFFFFFFFF parses as Int32 -1 in PowerShell, which makes -band a no-op
  # and lets $h overflow. Use explicit unsigned constants to stay 32-bit.
  $prime = [uint64]16777619
  $mask  = [uint64]4294967295   # 0xFFFFFFFF
  $h = [uint64]2166136261
  for ($i = 0; $i -lt $s.Length; $i++) {
    $h = $h -bxor ([uint64]([int]$s[$i] -band 0xff))
    $h = ($h * $prime) -band $mask
  }
  return ('{0:x8}' -f [uint32]$h)
}
function Get-Fence([string]$p) { $e = (($p -split '\.')[-1]).ToLower(); if ($FENCE.ContainsKey($e)) { $FENCE[$e] } else { '' } }

# 3) Walk the folder and collect readable text files.
$files = New-Object System.Collections.ArrayList
Get-ChildItem -LiteralPath $root -Recurse -File -Force -ErrorAction SilentlyContinue | ForEach-Object {
  $rel = $_.FullName.Substring($root.Length).TrimStart('\','/').Replace('\','/')
  $segs = $rel.Split('/')
  if ($segs | Where-Object { $skipDirs -contains $_ }) { return }
  if ($_.Name -match $skipExt) { return }
  if ($_.Length -gt $maxBytes) { return }
  $text = $null
  try { $text = [IO.File]::ReadAllText($_.FullName) } catch { return }
  if ($text.IndexOf([char]0) -ge 0) { return }   # NUL byte -> binary, skip
  [void]$files.Add([pscustomobject]@{ path = $rel; hash = (Get-Fnv $text); bytes = $_.Length; text = $text; dupOf = $null })
}
$files = @($files | Sort-Object path)
if ($files.Count -eq 0) { Write-Host 'No readable text files found in that folder.'; return }

# 4) Dedupe identical files by content hash.
$seen = @{}; $saved = 0
foreach ($f in $files) {
  if ($seen.ContainsKey($f.hash)) { $f.dupOf = $seen[$f.hash]; $saved += [math]::Ceiling($f.text.Length / 4) }
  else { $seen[$f.hash] = $f.path }
}
$rootHash = Get-Fnv ((($files | ForEach-Object { $_.path + ':' + $_.hash }) -join "`n"))
$uniqueChars = 0; foreach ($f in $files) { if (-not $f.dupOf) { $uniqueChars += $f.text.Length } }
$tokens = [math]::Ceiling($uniqueChars / 4)

# 5) Emit Markdown (the format models read best).
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# $srcName - codebase context")
[void]$sb.AppendLine('')
[void]$sb.AppendLine("<!-- AI context | source: $srcName | root: $rootHash | $($files.Count) files | ~$tokens tokens" + $(if ($saved) { " | $saved tokens saved by dedup" } else { '' }) + " | generated by bfx-ingest -->")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Files')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('```')
foreach ($f in $files) { [void]$sb.AppendLine('  ' + $f.path + $(if ($f.dupOf) { '  (= ' + $f.dupOf + ')' } else { '' })) }
[void]$sb.AppendLine('```')
[void]$sb.AppendLine('')
foreach ($f in $files) {
  if ($f.dupOf) { continue }
  [void]$sb.AppendLine("### $($f.path)")
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('```' + (Get-Fence $f.path))
  [void]$sb.AppendLine($f.text)
  [void]$sb.AppendLine('```')
  [void]$sb.AppendLine('')
}

# 6) Write the file next to the chosen folder, report, and reveal it.
$out = Join-Path (Split-Path -Parent $root) ($srcName + '-context.md')
[IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host ''
Write-Host ("bfx-ingest: {0} files -> ~{1} tokens{2}" -f $files.Count, $tokens, $(if ($saved) { " (saved $saved via dedup)" } else { '' }))
Write-Host ("root hash {0}" -f $rootHash)
Write-Host ("saved -> {0}" -f $out)
try { Start-Process explorer.exe "/select,`"$out`"" } catch {}
